apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: docker.io/krn010/frontend

---

apiVersion: v1
kind: Pod
metadata:
  name: catalogue
spec:
  initContainers:
    - name: parameters-pull
      image: docker.io/krn010/parameter-store-init-container-image
      imagePullPolicy: Always
      env:
        - name: PARAMS
          value: "dev.roboshop.docdb.endpoint dev.roboshop.docdb.username dev.roboshop.docdb.password"
  containers:
    - name: catalogue
      image: docker.io/krn010/catalogue
---
apiVersion: v1
kind: Pod
metadata:
  name: user
spec:
  containers:
    - name: user
      image: docker.io/krn010/user
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
spec:
  containers:
    - name: cart
      image: docker.io/krn010/cart
---
apiVersion: v1
kind: Pod
metadata:
  name: payment
spec:
  containers:
    - name: payment
      image: docker.io/krn010/payment
---
apiVersion: v1
kind: Pod
metadata:
  name: shipping
spec:
  containers:
    - name: shipping
      image: docker.io/krn010/shipping
---
apiVersion: v1
kind: Pod
metadata:
  name: dispatch
spec:
  containers:
    - name: dispatch
      image: docker.io/krn010/dispatch