apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: docker.io/krn010/frontend

---

apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    app: catalogue
spec:
  initContainers:
    - name: parameters-pull
      image: docker.io/krn010/parameter-store-init-container-image
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /parameters
          name: parameters
      env:
        - name: PARAMS
          value: "dev.roboshop.catalogue.MONGO_URL,MONGO_URL"

  containers:
    - name: catalogue
      image: docker.io/krn010/catalogue
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /parameters
          name: parameters

  volumes:
    - name: parameters
      emptyDir: {}

---
apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    app: user
spec:
  containers:
    - name: user
      image: docker.io/krn010/user
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
spec:
  containers:
    - name: cart
      image: docker.io/krn010/cart
---
apiVersion: v1
kind: Pod
metadata:
  name: payment
  labels:
    app: payment
spec:
  containers:
    - name: payment
      image: docker.io/krn010/payment
---
apiVersion: v1
kind: Pod
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  containers:
    - name: shipping
      image: docker.io/krn010/shipping
---
apiVersion: v1
kind: Pod
metadata:
  name: dispatch
  labels:
    app: dispatch
spec:
  containers:
    - name: dispatch
      image: docker.io/krn010/dispatch

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    app: catalogue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    app: shipping
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dispatch
spec:
  selector:
    app: dispatch
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: frontend
  spec:
    ingressClassName: nginx
    rules:
      - host: frontend-dev.kdevops.online
        http:
          paths:
            - pathType: Prefix
              backend:
                service:
                  name: frontend
                  port:
                    number: 80
              path: /
